In [1]:
from toolbox.db_access.postgres import PSQManagement

In [28]:
psqm = PSQManagement()

In [32]:
columns = ["id as offer_id", "title", "description", "contract_id", "recruiter_id", "department_id", 
           "industry_id", "location", "latitude", "longitude", "created_at"]
OFFER_NUMBER = 10000

In [33]:
df = psqm.get_df_from_query(f"SELECT {', '.join(columns)} FROM offers ORDER BY created_at DESC LIMIT {OFFER_NUMBER};")

In [35]:
df.to_csv("./../data/offers.csv", index=False)

In [50]:
recruiter_columns = [
    "id as recruiter_id",
    "industry_id",
    "organization_id"
]
df_recruiters = psqm.get_df_from_query(f"SELECT {', '.join(recruiter_columns)} FROM recruiters WHERE id IN ({','.join(df.recruiter_id.astype(str).tolist())}) LIMIT {OFFER_NUMBER};")

In [67]:
df_recruiters.to_csv("./../data/recruiters.csv", index=False)

In [60]:
organization_columns = [
    "id as organization_id",
    "name",
    "location", 
    "latitude",
    "longitude", 
    "industry_id",
    "description",
    "siret"
]
df_organization = psqm.get_df_from_query(f"SELECT {', '.join(organization_columns)} FROM organizations WHERE id IN ({','.join(df_recruiters.organization_id.astype(str).tolist())}) LIMIT {OFFER_NUMBER};")

In [63]:
df_organization.shape

(885, 8)

In [65]:
df_organization.to_csv("./../data/organizations.csv", index=False)

In [66]:
df_organization

,organization_id,name,location,latitude,longitude,industry_id,description,siret
0,11,Burson-Marsteller i&e,,NaN,NaN,19,Burson-Marsteller i&e est une agence conseil e...,None
1,34,Aspen RH,"21, rue Royale – 75008 Paris",NaN,NaN,20,Aspen rh est un cabinet de recrutement de cadr...,
2,65,LEROY MERLIN RHONE ALPES,,NaN,NaN,10,"Oser, expérimenter, tenter et se tromper, tent...",
3,108,Sogeti High Tech,,NaN,NaN,9,Sogeti High Tech a développé un éventail d’exp...,None
4,361,Apsynth Publishing,"Boulogne-Billancourt, France",48.839695,2.239912,17,apsynth est l’agence web basée à Boulogne Bill...,None
5,402,Karbone,,NaN,NaN,9,Karbone est un cabinet de conseil en organisat...,
6,666,FRICHTI,,NaN,NaN,17,"On cuisine ou on Frichti ?\r\nFrichti, c’est p...",
7,677,CONVERTEO,,NaN,NaN,9,Converteo est un cabinet de conseil spécialist...,
8,699,DigitasLbi,"34 Rue du Chemin Vert, Paris, France",48.858050,2.373355,19,Le réseau DigitasLBi accompagne les plus grand...,None
9,751,WeScale,None,NaN,NaN,16,"WeScale en quelques mots, c’est à la fois une ...",None
10,797,Carrefour,,NaN,NaN,10,N° 1 de la grande distribution en Europe et n°...,None
11,915,MOBISKILL,,NaN,NaN,16,Mobiskill est une start-up du recrutement créé...,None
12,1042,HENRI 8,None,NaN,NaN,19,Nous sommes une agence de conseil en communica...,None
13,1073,Wisembly,,NaN,NaN,17,Nous développons des applications en ligne pou...,
14,1105,Groupama Loire Bretagne,"23 Boulevard Solférino, Rennes, France",48.104458,-1.669016,6,Nous sommes une entreprise mutualiste répartie...,
15,1189,Groupe Bertrand,,NaN,NaN,13,Présent depuis plus de vingt ans sur le marché...,
16,1278,Pixie Services,None,NaN,NaN,20,Recruitment agency specialised in providing be...,None
17,1290,Eye Web,None,NaN,NaN,7,EYEWEB est une société en pleine croissance sp...,None
18,1293,Indie United SAS,None,NaN,NaN,17,"GRAFITEE, boutique de T-shirts et de Sweats or...",None
19,1305,Fove,None,NaN,NaN,19,« FOVE est une agence de créativité relationne...,None
20,1326,Effilab,None,NaN,NaN,5,EFFILAB est une agence de publicité à la perfo...,53120556500058
21,1524,VISEO,,NaN,NaN,16,"\r\nLe Groupe Viseo (1200 salariés), spéciali...",None
22,1537,MEDIA INSTITUTE,,NaN,NaN,17,Media Institute est l'organisme de formation d...,None
23,1583,AGENCE R RECRUTEMENT,,NaN,NaN,19,Agence R Recrutement est un cabinet de recrute...,
24,1608,IKOULA NET,None,NaN,NaN,16,"Ikoula est specialiste de l’hebergement web, d...",None
25,1611,CCLD Recrutement,"43 Avenue de la Grande Armée, Paris, France",48.875319,2.288820,20,A la recherche de nouvelles affinités professi...,None
26,1640,Agence Baltazare,None,NaN,NaN,19,Baltazare est une agence digitale basée sur Pa...,None
27,1667,Société Générale,,NaN,NaN,6,Société Générale est l’un des 1ers groupes eur...,
28,1776,Impulse Partners,None,NaN,NaN,9,IMPULSE PARTNERS est un cabinet de conseil en ...,None
29,1870,Doctolib,,NaN,NaN,17,"Fondé en octobre 2013, Doctolib a pour objecti...",None
...,...,...,...,...,...,...,...,...
855,14123,plb,None,NaN,NaN,12,PLB Consultant est un centre de formation dédi...,None
856,14124,SKEMA,None,NaN,NaN,12,SKEMA Business School est une école supérieure...,None
857,14132,SOPHYSA,None,NaN,NaN,21,"Notre entreprise, SOPHYSA, créée en 1976, déve...",None
858,14133,Mutuelle de Poitiers Assurances,None,NaN,NaN,6,"Avec plus de 180 ans d’existence, la Mutuelle ...",None
859,14139,Monsieur SLOOP,None,NaN,NaN,19,Monsieur SLOOP est une agence de communication...,None
860,14140,CDL,None,NaN,NaN,18,"CDL développement, cabinet spécialisé dans la ...",None
861,14141,Picocorner,None,NaN,NaN,10,Picocorner est une startup proposant un servic...,None
862,14149,Imagence,None,NaN,NaN,16,Imagence est une agence interactive qui dévelo...,None
863,14150,Cabinet MADERE,None,NaN,NaN,16,"Créée en 2012, la société Konectik se position...",None
864,14162,TALENTSKILLS,None,NaN,NaN,20,"Créé en 2005 et implanté à Paris et à Orléans,...",None
865,14163,SAFERAIL,,NaN,NaN,15,Expert en Contrôle-Commande et Signalisation f...,
866,14168,RH PERFORMANCES,None,NaN,NaN,20,"Notre rêve, chez RH Performances, c’est de per...",None
867,14169,ARMIS,None,NaN,NaN,19,Tu veux rejoindre une pépite française de la R...,None
868,14174,OCPR Events,None,NaN,NaN,9,"S’appuyant sur quinze années d’expertise, la s...",None
869,14175,want-id,None,NaN,NaN,10,\r\nVous qui lisez cette annonce ! J’ai une in...,None
870,14177,Dermalogica,None,NaN,NaN,10,Créée il y a plus de 30 ans en Californie par ...,None
871,14178,Skynet Worldwide Express,None,NaN,NaN,18,"SKYNET France, membre du réseau mondial SKYNET...",None
872,14180,SENTELIS,None,NaN,NaN,16,Sentelis est un cabinet de conseil en Stratégi...,None
873,14181,AltR,None,NaN,NaN,17,AltR est la première application altruiste qui...,None
874,14186,Verduron LTD,None,NaN,NaN,20,"Verduron recruitment is an Executive, Internat...",None
875,14189,KACILEO,None,NaN,NaN,20,Conseil en développement RH et recrutement,None
876,14190,GUY HOQUET,None,NaN,NaN,14,Bonjour et bienvenue à l’agence Guy Hoquet l’I...,None
877,14191,Compagnie des Salins du Midi et des Salines de...,None,NaN,NaN,2,Le Groupe Salins existe depuis plus de 150 ans...,None
878,14194,Novajob,None,NaN,NaN,20,"Dans le cadre de son développement, notre clie...",None
879,14196,Global Partner,None,NaN,NaN,9,"Entreprise très dynamique, de taille humaine, ...",None
880,14203,CASTELIS,None,NaN,NaN,17,Castelis : Great Place To Geek ! \r\n\r\nCaste...,None
881,14204,SOLU-WATT,None,NaN,NaN,15,"Conçue en 1992, la société appelée Accord Diff...",None
882,14208,Avalanche Aménagements Utilitaires,None,NaN,NaN,1,La société AVALANCHE Aménagements Utilitaires ...,None
883,14210,KaizenData,None,NaN,NaN,16,Kaizen Data est un éditeur de solutions logici...,None
884,14211,In&Fi Crédits,None,NaN,NaN,6,"Filiale de Global Franchise Crédit, le réseau ...",None

In [2]:
psqm = PSQManagement()

In [4]:
df = psqm.get_df_from_query("SELECT id, i18n_name FROM industries")

In [6]:
df.to_csv("./../data/industries.csv", index=False)

In [7]:
df = psqm.get_df_from_query("SELECT id, i18n_name FROM departments")

In [8]:
df

     id                         i18n_name
0     1                             sales
1     2                         marketing
2     3                               art
3     4                             strat
4     5                             admin
5     6                               law
6     7                       engineering
7     8                                it
8     9                                hr
9    10                         logistics
10   11                        production
11   12                             archi
12   13                            health
13   14                 financial_markets
14   15                 corporate_finance
15   16                     communication
16  101     d2_sales_business_development
17  102               d2_customer_service
18  103                      d2_marketing
19  104                  d2_communication
20  105           d2_design_art_direction
21  106       d2_research_and_development
22  107  d2_industrial_design_engineering
23  108             d2_production_quality
24  109          d2_business_intelligence
25  110      d2_it_infrastructure_network
26  111                 d2_it_backend_dev
27  112                d2_it_frontend_dev
28  113               d2_it_fullstack_dev
29  114                  d2_it_mobile_dev
30  115          d2_it_product_management
31  116                d2_human_resources
32  117             d2_logistics_sourcing
33  118                  d2_legal_and_tax
34  119         d2_cosulting_and_strategy
35  120             d2_financial_analysis
36  121            d2_audit_and_accouting
37  122                      d2_insurance
38  123                          d2_admin

In [6]:
df.to_csv("./../data/industries.csv", index=False)